version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - claude-network
    depends_on:
      - api

  api:
    image: claude-api
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    networks:
      - claude-network

networks:
  claude-network:
    driver: bridge
